name: survey_engine.dart
version: 0.1.0
description: >-
  The current package is a project of Influenzanet. The package provides a reusable survey parsing library for Influenzanet surveys. 
  It can be integrated easily to develop flutter applications.
homepage: https://influenzanet.github.io/
documentation: https://github.com/influenzanet/survey-engine.dart/wiki
issue_tracker: https://github.com/influenzanet/survey-engine.dart/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  pedantic: ^1.8.0

dev_dependencies:
  test: ^1.6.0
  test_coverage: ^0.4.1

